### ISSUE TITLE
It needs more external memory

### ISSUE THREAD

**Issue by tommythorn** [gregdavill/ArcticKoala#1]
It had to be said :)

**Comment by gregdavill** [comment]
64Mbit isn't enough? :(

**Comment by gregdavill** [comment]
Also, for what it's worth. The QFN72 package does not have the I/O resources to drive any form of DDR2/3/4 memory. That only appears to be available in the BGA packages.

**Comment by tommythorn** [comment]
It’s your board, your rules.  I’m just here to speak up for the memory pigs.  Given the purpose of this board, SPI is probably ideal (way easier to use), but you are not going to drive video or run desktop Linux with this.
